name: mir
channels:
  - defaults
  - conda-forge
dependencies:
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - matplotlib=3.0.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=6.0.0
  - numpy=1.16.4
  - python=3.7.0
  - scipy=1.4.1

