name: mir
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh=2.0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.12.3
  - cython=0.29.13
  - ipykernel=5.1.2
  - ipympl=0.5.6
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - librosa=0.6.3
  - markupsafe=1.1.1
  - matplotlib=3.0.1
  - matplotlib-base=3.1.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=6.0.0
  - numba=0.45.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - python=3.7.0
  - python-dateutil=2.8.0
  - python_abi=3.7
  - qt=5.9.7
  - qtconsole=4.5.4
  - scikit-learn=0.20.3
  - scipy=1.4.1
  - setuptools=41.0.1
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2

